#!/usr/bin/env perl

use FindBin;
use lib $FindBin::Bin;
use lib $FindBin::Bin . "/modules";

use JSON;
use Zan::RPC;
use Data::Dumper;

# Read configuration data from this file
require("api_config.pl");

if ($ARGV[0] eq "") {
	print "Usage:\n";
	print "\tlims_sample_data.pl [flowcell_id]\n";
	print "\n";
	exit(1);
}

# This should be the base install directory of LIMS
my $modulesURL = $ZAN_API_URL;

# This is generated by logging in to the dashboard, going to Tools -> Edit Your User Settings, Remote API Tokens
my $authToken = $ZAN_API_AUTH_TOKEN;

my $fnName = "fc_getSamples";

$rpc = new Zan::RPC($modulesURL, $authToken);

$result = $rpc->call("MolBio.ngs_remoteAPI." . $fnName, $ARGV[0]);


if (!$result) {
  print "Flowcell not found.\n";
} else {
	my $json = new JSON;
	print $json->encode($result);
}
